[project]
name = "prj02"
version = "0.1.0"
description = "Proyecto Python estándar con layout src"
authors = [
    { name = "Mario Robledo" }
]

requires-python = ">=3.11"

[tool.pytest.ini_options]
pythonpath = ["src"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
